### ISSUE TITLE
Why no Releases?

### ISSUE THREAD

**Issue by CGminded** [rhelmot/smw-coop#15]
I came here expecting to just download a ROM file of the game, why not put a ready ROM file in the Releases section?

I found a ready ROM of this in YT vid - https://www.mediafire.com/file/npxdonfrzm3drl5/Super+Mario+World+Co-op+Hack.rar/file

**Comment by rhelmot** [comment]
Posting ROMs is illegal ;)

**Comment by CGminded** [comment]
.smc ROM file can be posted in code section where all the files are located, at least this guy did it and it's fine - https://github.com/raaka1/MARI-O-NEAT/tree/master/Mario_rom

**Comment by rhelmot** [comment]
Pretty sure that's also illegal!

**Comment by rhelmot** [comment]
I can, however, post an IPS patch. Those are not illegal. I will get around to this at some point.

**Comment by CGminded** [comment]
ok, thank you

**Comment by rhelmot** [comment]
You can download co-op.ips from here https://github.com/rhelmot/smw-coop/releases/tag/v0.0.1

**Comment by thomasgoldstein** [comment]
Hello @rhelmot. I believe there is something wrong with the 0.0.1 ips patch. Lunar Compress says it is not an IPS file. I tried another random IPS program (IPS Peek), which also failed to open it. I downloaded the ips file twice to make sure. It's 125 KB but I guess it got corrupted during uploading or something. Thanks.

**Comment by rhelmot** [comment]
Ugh. It seems that even though I told my IPS patcher to produce an IPS file it actually produced a BPS file. Hold tight, I'll fix it.

**Comment by rhelmot** [comment]
Fixed. You should now be able to download either an IPS or a BPS patch depending on your mood.
