### ISSUE TITLE
asar: 'co-op.asm' is not an asar command

### ISSUE THREAD

**Issue by soydemadrid** [rhelmot/smw-coop#2]
Hi, sorry but I'm struggling a bit with your build instructions. I'm new to patching smw so forgive me!

I just wanted to have a go on a good co-op version so I got a clean smw rom and followed your instructions, but I may have done it wrong.

I installed npm on ubuntu 17.04 - installed asar as the github repo instructions (I haven't used asar before so I hope this is the right application?), did the lunar magic part in Windows VM, then back on linux I ran this from the smw-coop-master directory:

`#asar co-op.asm rom/Super\ Mario\ World\ CO-OP\ \(U\)\ \[\!\].smc`

but it just gives me the following error:

> asar: 'co-op.asm' is not an asar command. See 'asar --help'.

Thanks for any help with this :)

**Comment by rhelmot** [comment]
I don't think asar is a npm module! the only place I'm aware to download it is through the SMW Central tools section.

**Comment by soydemadrid** [comment]
Hi that explains things! Here is where I got asar as an NPM:

https://www.npmjs.com/package/asar

haha. I've removed that and done it your way and it works! Thank you :)
